const projectsInformation = [
  {
    id: 1,
    image: "https://i.postimg.cc/tCt1PwbN/documental.webp",
    video: "/videos/Documental En Conflicto.mp4",
    text: "Documental En Conflicto",
    category: "documentales",
    url: null,
  },
  {
    id: 2,
    image: "https://i.postimg.cc/sDZVBgdq/home-picture.jpg",
    video: null,
    text: "Libera",
    category: "transmedia",
    url: "https://liberapage.netlify.app/",
  },
  {
    id: 3,
    image: "https://i.postimg.cc/XN95nZsz/luna-ld.png",
    video: null,
    text: " LD Luna",
    category: "musicales",
    url: "https://drive.google.com/file/d/1Tbh4mqu_05XuKPJpuUVOIsQ7wMLszQNp/view?usp=drive_link",
  },
  {
    id: 4,
    image: "https://i.postimg.cc/3JSxhYQq/ma-ld.png",
    video: null,
    text: "LD Ma",
    category: "musicales",
    url: "https://drive.google.com/file/d/115_91BqtWI6eEvdzsX3G5lO0ld_vV3Lg/view?usp=drive_link",
  },
  {
    id: 5,
    image: "https://i.postimg.cc/4NKrKghq/taki-ld.png",
    video: null,
    text: "LD Taki Tac",
    category: "musicales",
    url: "https://drive.google.com/file/d/1-ajoFKm1fOxTYl3g5czbxty2cG33y4tG/view?usp=drive_link",
  },
  {
    id: 6,
    image: "https://i.postimg.cc/wj9J361Q/corto-elfinal.png",
    video: "/videos/corto-final.mp4",
    text: "Sin salida",
    category: "cortos",
    url: null,
  },
  {
    id: 7,
    image: "https://i.postimg.cc/YqwGvk5S/matizando.webp",
    video: "/videos/Matizando Ana Sanz.mp4",
    text: "Matizando Ana sanz",
    category: "animacion",
    url: null,
  },
  {
    id: 8,
    image: "https://i.postimg.cc/Vst0s5HT/invitacion-D.webp",
    video: "/videos/Invitación Documental.mp4",
    text: "Invitación documental en conflicto",
    category: "animacion",
    url: null,
  },
  {
    id: 9,
    image: "https://i.postimg.cc/KvStS7FV/doc-ld.png",
    video: null,
    text: "Documental LD",
    category: "documentales",
    url: "https://drive.google.com/file/d/1bZB7kcoNVJSWQWoMq32dHcfvES5BzwOP/view",
  },
  {
    id: 10,
    image: "https://i.postimg.cc/LX96FNym/filminuto.png",
    video: null,
    text: "Filminuto Dónde estás",
    category: "cortos",
    url: "https://drive.google.com/file/d/1hgGKgLC8a7olvON10XzEpdEkXUNQXXCl/view",
  },
];

export default projectsInformation;
