const projectsInformation = [
  {
    id: 1,
    image: "https://i.postimg.cc/RZ305DTj/image-Home.jpg",
    video: "/videos/8.Animación-Campaña.mp4",
    text: "imagen",
    category: "musicales",
    url: null,
  },
  {
    id: 2,
    image: "https://i.postimg.cc/sDZVBgdq/home-picture.jpg",
    video: "/videos/8.Animación-Campaña.mp4",
    text: "Libera",
    category: "transmedia",
    url: "https://liberapage.netlify.app/",
  },
  {
    id: 3,
    image: "https://i.postimg.cc/RZ305DTj/image-Home.jpg",
    video: "/videos/8.Animación-Campaña.mp4",
    text: "imagen",
    category: "documentales",
    url: null,
  },
  {
    id: 4,
    image: "https://i.postimg.cc/RZ305DTj/image-Home.jpg",
    video: "/videos/8.Animación-Campaña.mp4",
    text: "imagen",
    category: "cortos",
    url: null,
  },
  {
    id: 5,
    image: "https://i.postimg.cc/RZ305DTj/image-Home.jpg",
    video: "/videos/8.Animación-Campaña.mp4",
    text: "imagen",
    category: "musicales",
    url: null,
  },
  {
    id: 6,
    image: "https://i.postimg.cc/RZ305DTj/image-Home.jpg",
    video: "/videos/8.Animación-Campaña.mp4",
    text: "imagen",
    category: "musicales",
    url: null,
  },
  {
    id: 7,
    image: "https://i.postimg.cc/RZ305DTj/image-Home.jpg",
    video: "/videos/8.Animación-Campaña.mp4",
    text: "imagen",
    category: "musicales",
    url: null,
  },
];

export default projectsInformation;
