const projectsInformation = [
  {
    id: 1,
    image: "https://i.postimg.cc/tCt1PwbN/documental.webp",
    video: "/videos/Documental En Conflicto.mp4",
    text: "Documental En Conflicto",
    category: "documentales",
    url: null,
  },
  {
    id: 2,
    image: "https://i.postimg.cc/sDZVBgdq/home-picture.jpg",
    video: "/videos/8.Animación-Campaña.mp4",
    text: "Libera",
    category: "transmedia",
    url: "https://liberapage.netlify.app/",
  },
  {
    id: 3,
    image: "https://i.postimg.cc/XN95nZsz/luna-ld.png",
    video: "/videos/LD  LUNA OFFICIAL VIDEO.mp4",
    text: " LD Luna",
    category: "musicales",
    url: null,
  },
  {
    id: 4,
    image: "https://i.postimg.cc/3JSxhYQq/ma-ld.png",
    video: "/videos/LD MA OFFICIAL VIDEO.mp4",
    text: "LD Ma",
    category: "musicales",
    url: null,
  },
  {
    id: 5,
    image: "https://i.postimg.cc/4NKrKghq/taki-ld.png",
    video: "/videos/LD TAKI TAC OFFICIAL VIDEO.mp4",
    text: "LD Taki Tac",
    category: "musicales",
    url: null,
  },
  {
    id: 6,
    image: "https://i.postimg.cc/wj9J361Q/corto-elfinal.png",
    video: "/videos/corto-final.mp4",
    text: "El Final",
    category: "cortos",
    url: null,
  },
  {
    id: 7,
    image: "https://i.postimg.cc/YqwGvk5S/matizando.webp",
    video: "/videos/Matizando Ana Sanz.mp4",
    text: "Matizando Ana sanz",
    category: "animacion",
    url: null,
  },
  {
    id: 8,
    image: "https://i.postimg.cc/Vst0s5HT/invitacion-D.webp",
    video: "/videos/Invitación Documental.mp4",
    text: "Invitación Documental",
    category: "animacion",
    url: null,
  },
];

export default projectsInformation;
